### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by philiprbrenan** [oodler577/p5-Sub-Genius#1]
Hi **Brett**:

Might it be possible to show your code in operation using a GitHub action as in:

https://github.com/philiprbrenan/TreeTrek/blob/main/.github/workflows/main.yml

This provides immediate gratification for the casual observer by eliminating the need to download and install code.

**Comment by oodler577** [comment]
This is a good idea, thank you! TreeTrek looks interesting, will have to check it out. My backlog is groooowing exponentially :-)

Uploaded some tests in a bit, so it's a good time to kick off something of an automated test suite.

**Comment by oodler577** [comment]
@philiprbrenan - this is in the branch I am preparing for release. Thanks, again.
